services:
  _defaults:
    autowire: true
    autoconfigure: true

  App\Enveloping\Factory\:
    resource: '../src/Factory/'

  App\Enveloping\Codec\EnvelopeBuiltInAttributeCodec:
    tags:
      - { name: 'enveloping.attribute_codec' }

  App\Enveloping\Registry\EnvelopeAttributeCodecRegistry:
    arguments:
      $codecs: !tagged_iterator enveloping.attribute_codec

  App\Enveloping\Codec\EnvelopeCodec: ~

  App\Enveloping\Codec\EnvelopeJsonCodec: ~
